example/auth_u/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import RegistrationView, ProfileView
from . import views

app_name = 'auth_u'

urlpatterns = [
    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='auth_u/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='auth_u:login'), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('api/users/', views.UserListCreateAPIView.as_view(), name='user-list-create'),
    path('api/users/<int:pk>/', views.UserRetrieveUpdateDestroyAPIView.as_view(), name='user-retrieve-update-destroy'),
]

example/example/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('auth_u.urls', 'auth_u'))),
    path('reports/', include(('reports.urls', 'reports'))),
    path('docs/', TemplateView.as_view(
        template_name='docs.html',
        extra_context={'schema_url':'api_schema'}
        ), name='swagger-ui'),
    path('api_schema/', get_schema_view(
        title='API Schema',
        description='Guide for the REST API'
    ), name='api_schema'),
]

example/reports/urls.py
from django.urls import path
from .views import ReportCreateView, ReportDetailView, ReportListView, ReportListAPIView, ReportDetailAPIView, ReportCreateAPIView


app_name = 'reports'


urlpatterns = [
    path('create/', ReportCreateView.as_view(), name='report_create'),
    path('list/', ReportListView.as_view(), name='report_list'),
    path('detail/<int:pk>/', ReportDetailView.as_view(), name='reports_detail'),
    path('api/create/', ReportCreateAPIView.as_view(), name='report_create_api'),
    path('api/list/', ReportListAPIView.as_view(), name='report_list_api'),
    path('api/detail/<int:pk>/', ReportDetailAPIView.as_view(), name='report_detail_api'),
]

example/reports/models.py
from django.db import models
from django.contrib.auth.models import User

class Report(models.Model):
    STATUS_CHOICES = (
        ('new', 'Новое'),
        ('confirmed', 'Подтверждено'),
        ('rejected', 'Отклонено'),
    )
    title = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car_number = models.CharField(max_length=20)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')

    def __str__(self):
        return f"{self.title} #{self.pk} - {self.car_number}"

example/auth_u/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput()
    )
    email = forms.EmailField(
        widget=forms.EmailInput()
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

example/reports/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('title', 'description', 'car_number', 'status', 'user') 

example/auth_u/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from .forms import RegistrationForm
from rest_framework import generics
from django.contrib.auth.models import User
from .serializers import UserSerializer


class RegistrationView(SuccessMessageMixin, CreateView):
    form_class = RegistrationForm
    template_name = 'auth_u/register.html'
    success_url = '/'
    success_message = "Пользователь создан"


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'auth_u/profile.html'


class UserListCreateAPIView(generics.ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

example/reports/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView
from .forms import ReportForm
from .models import Report
from django.urls import reverse_lazy

class ReportCreateView(LoginRequiredMixin, CreateView):
    model = Report
    form_class = ReportForm
    template_name = 'reports/reports_create.html'
    success_url = reverse_lazy('reports:report_list')

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ReportListView(ListView):
    model = Report
    template_name = 'reports/report_list.html'
    context_object_name = 'reports'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class ReportDetailView(DetailView):
    model = Report
    template_name = 'reports/reports_detail.html'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from .models import Report
from .serializers import ReportSerializer

class ReportCreateAPIView(generics.CreateAPIView):
    queryset = Report.objects.all()
    serializer_class = ReportSerializer
    permission_classes = [IsAuthenticated]
    

class ReportListAPIView(generics.ListAPIView):
    queryset = Report.objects.all()
    serializer_class = ReportSerializer
    permission_classes = [IsAuthenticated]

class ReportDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Report.objects.all()
    serializer_class = ReportSerializer
    permission_classes = [IsAuthenticated]

example/auth_u/templates/auth_u/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit">Login</button>
    </form>
{% endblock %}

example/auth_u/templates/auth_u/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
    <h1>Welcome to your profile!</h1>
    <h1>Your Username: {{ request.user.username }}</h1>
{% endblock %}

example/auth_u/templates/auth_u/register.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}

        <label for={{ form.username.id_for_label }}>Username</label>
        {{ form.username }} <br> <br>
        <label for={{ form.username.id_for_label }}>Email</label>
        {{ form.email }} <br> <br>
        <label for={{ form.password1.id_for_label }}>Password</label>
        {{ form.password1 }}<br> <br>
        <label for={{ form.password2.id_for_label }}>Confirm password</label>
        {{ form.password2 }}<br> <br>

        <button type="submit">Submit</button>
    </form>
{% endblock %}

example/reports/templates/reports/report_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
        }
        h1, h2 {
            color: #007bff;
            margin-bottom: 20px;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        li {
            margin-bottom: 10px;
        }
        button[type="submit"] {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Report List</h1>
        <h1>Profile: {{ request.user.username }}</h1>
        <ul>
            {% for report in reports %}
            <li>
                <a href="{% url 'reports:reports_detail' pk=report.pk %}" class="text-decoration-none">{{ report.title }}</a> - Status: {{ report.status }}
            </li>
            {% endfor %}
        </ul>

        <form action="{% url 'auth_u:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Выйти</button>
        </form>

        <hr>

        <h2>Добавить новую репорт</h2>
        <form action="{% url 'reports:report_create' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

example/reports/templates/reports/reports_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
        }
        h1 {
            color: #007bff;
            margin-bottom: 20px;
        }
        button[type="submit"] {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Create Report</h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

example/reports/templates/reports/reports_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ object.title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
        }
        h1 {
            color: #007bff;
        }
        p {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ object.title }}</h1>
        <div>
            <p><strong>Description:</strong> {{ object.description }}</p>
            <p><strong>Car Number:</strong> {{ object.car_number }}</p>
            <p><strong>Status:</strong> {{ object.status }}</p>
            <p><strong>User:</strong> {{ object.user }}</p>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

example/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<header>
    {% if user.is_authenticated %}
        <form method="post" action="{% url 'auth_u:logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Logout</button>
        </form>
    {% else %}
        <a href="{% url 'auth_u:register' %}" class="btn btn-primary">Register</a>
        <a href="{% url 'auth_u:login' %}" class="btn btn-success">Login</a>
    {% endif %}
</header>
<div class="container mt-5">
    {% block content %}{% endblock %}
</div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

example/templates/docs.html
<!DOCTYPE html>
<html>
  <head>
    <title>School Service Documentation</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout"
      })
    </script>
  </body>
</html>